---
- name: Install SSSD
  yum:
    name: sssd
    state: latest
  become: true

- name: Setup SSSD (1/3)
  template: src=etc/sssd/sssd.conf.j2 dest=/etc/sssd/sssd.conf mode=0600
  become: true

- name: Setup SSSD (2/3)
  command: /usr/sbin/authconfig --enablesssd --enablesssdauth --enablelocauthorize --disablemkhomedir --update
  become: true

- name: Setup SSSD (3/3)
  service: name=sssd state=started enabled=yes
  become: true